const paragraphs = [
    "The sun peeked through the window blinds, casting long shadows across the room. It was a serene morning, perfect for a leisurely stroll or perhaps a quiet cup of coffee on the porch. Birds chirped outside, adding to the peaceful ambiance. However, amidst this tranquility, there was a sense of urgency—a task waiting to be completed, a goal to be achieved. The keyboard lay patiently on the desk, inviting fingers to dance upon its keys. With a deep breath, the typing test began.",
    "Each keystroke echoed in the quiet room, punctuating the air with a rhythmic melody. The challenge lay not just in speed but also in accuracy—the delicate balance between swift fingers and a focused mind. Mistakes were inevitable, but every error served as a lesson, a chance to improve and refine one's typing skills. As the words flowed effortlessly onto the screen, a sense of satisfaction washed over the typist—a tangible manifestation of progress made through dedication and practice.",
    "The typing test was not merely a game but a testament to perseverance and determination. It was a journey of self-improvement, a quest to conquer the ever-elusive mastery of the keyboard. With each passing minute, the typist delved deeper into the challenge, pushing boundaries and surpassing limitations. There were moments of frustration, of doubt, but they were overshadowed by a relentless drive to succeed. Every word typed was a step forward, a victory in the ongoing battle against complacency.",
    "Time seemed to blur as the typing test continued, minutes melting into hours as the typist remained immersed in the task at hand. Distractions faded into the background, replaced by a singular focus on the screen before them. The outside world ceased to exist, its demands and pressures temporarily forgotten in the pursuit of excellence. In this moment, there was only the keyboard, the words, and the determination to conquer them.",
    "The typist's fingers moved with precision and purpose, navigating the keyboard with the grace of a seasoned musician playing a familiar tune. Each word appeared on the screen like a brushstroke on a canvas, contributing to the masterpiece taking shape before their eyes. There was a sense of flow, of harmony between mind and machine—a symbiotic relationship forged through countless hours of practice and dedication. In this intimate dance of fingers and keys, the typist found solace and fulfillment.",
    "The typing test served as a mirror, reflecting not only the typist's proficiency but also their resilience in the face of adversity. It was a measure of character as much as it was of skill—an opportunity to demonstrate grace under pressure and the ability to rise to the occasion. Whether facing a daunting time limit or a challenging passage, the typist remained steadfast, undeterred by the obstacles in their path. With each passing moment, they grew stronger, more confident in their abilities to overcome whatever challenges lay ahead.",
    "The typing test was a crucible, testing the typist's mettle and pushing them to their limits. It was a relentless gauntlet of words and letters, demanding both speed and accuracy in equal measure. Yet, amidst the chaos and pressure, there was a strange sense of exhilaration—a thrill that came from pushing oneself beyond what was thought possible. With each completed passage, the typist felt a surge of pride, knowing that they had conquered yet another challenge and emerged victorious.",
    "As the typing test neared its conclusion, the typist's fingers danced across the keyboard with renewed vigor, fueled by the knowledge that the end was in sight. Every word typed brought them one step closer to the finish line, one step closer to achieving their goal. And when the final keystroke was made, there was a sense of euphoria—a triumphant exhalation as the typist leaned back in their chair, basking in the glow of their accomplishment.",
    "The typing test may have ended, but its impact lingered long after the last word had been typed. It was a reminder of the power of perseverance, of the rewards that come from hard work and dedication. The typist carried this lesson with them as they ventured forth into the world, knowing that no challenge was too great to overcome with the right attitude and determination. And so, armed with newfound confidence, they faced whatever lay ahead, ready to tackle it with the same tenacity that had seen them through the typing test.",
    "In the end, the typing test was more than just a game—it was a journey of self-discovery and growth. It was a testament to the human spirit, to our capacity to learn and adapt in the face of adversity. And as the typist closed their laptop and reflected on the experience, they knew that they had emerged stronger, wiser, and more capable than before. For in the crucible of the typing test, they had found not only skill but also resilience, determination, and the unwavering belief that they could achieve anything they set their mind to."
]

  